In [2]:
# Import modules
import tweepy
import json
import pandas as pd

Credentials for accessing twitter APIs.

In [3]:
# credentials from twitter developer account
consumer_key = "Y1bYaFaYuRMVaqwqdX5y7dfPQ"
consumer_secret = "6tjbt4OQyGNDw0y6Looa5SZupgzH14QK5yjdNPXMUaDsLXM6bv"
access_key = "749178832452673536-gQdJoRxJzGMbOr89SJPNh6fUKpXI8TG"
access_secret = "x2sR2FOle8uWJAVKAU3HYR1FrlNGSoMDiwN51Vii6cTGB"

In [4]:
# Authenticate using consumer key and consumer secret
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)

In [5]:
auth.set_access_token(access_key, access_secret)
api = tweepy.API(auth)

In [6]:
# set user name for which you need tweets
user_name = "midasIIITD"

# User Details

In [7]:
# printing user details
item = api.get_user(user_name)
print("name: " + item.name)
print("screen_name: " + item.screen_name)
print("description: " + item.description)
print("statuses_count: " + str(item.statuses_count))
print("friends_count: " + str(item.friends_count))
print("followers_count: " + str(item.followers_count))

name: MIDAS IIITD
screen_name: midasIIITD
description: MIDAS is a group of researchers at IIIT-Delhi who study, analyze, and build different multimedia systems for society leveraging multimodal information.
statuses_count: 336
friends_count: 42
followers_count: 272

## Streaming user's tweets
Tweepy’s Cursor allows us to stream data from the query without having to manually query for more data in batches.

In [8]:
# array to store all the tweets
tweets = []

# open json file 
fp = open("python-task.jsonl","w+")

# can iterate over user's tweet using user_timeline keep tweet_mode as extended and to get full text of a tweet
for status in tweepy.Cursor(api.user_timeline, id = user_name, tweet_mode = "extended").items():
    tweet = {}
    
    # If a tweet is retweet then extract the favorite count from the tweet from which it is retweeted
    try:
        favorite = status.retweeted_status.favorite_count
    except AttributeError:
        favorite = status.favorite_count
    
    # Whether tweet contains media files(photos)
    try:
        images_count = len([medium['type'] == 'photo' for medium in status.entities['media']]) 
    except:
        
        # If no photo present in tweet return None
        images_count = None
    
    # Full Text of the tweet as tweet_mode is extended
    tweet["text"] = status.full_text
    
    # Date and Time of the tweet
    tweet["created_at"] = status.created_at.strftime("%c")
    
    # Number of favorites in the tweet
    tweet["favorite_count"] = favorite
    
    #Number of retweets in the tweet
    tweet["retweet_count"] = status.retweet_count
    
    # Number of Photos in the tweet
    tweet["images_count"] = images_count
    
    tweets.append(tweet)

# Dump all the tweets in JSONline format into the file
fp.write(json.dumps(tweets))
fp.close()

## Read JSON file and display in tabular form

In [9]:
# read JSONline file and display in tabular form
data = pd.read_json("python-task.jsonl", orient = 'columns')

In [10]:
# Display JSON data
data

,created_at,favorite_count,images_count,retweet_count,text
0,2019-04-07 14:17:29,0,NaN,0,"@himanchalchandr Meanwhile, complete CV/NLP ta..."
1,2019-04-07 14:17:09,0,NaN,0,@sayangdipto123 Submit as per the guideline ag...
2,2019-04-07 11:43:24,1,NaN,1,We request all students whose interview are sc...
3,2019-04-07 06:55:19,5,NaN,2,"Other queries: ""none of the Tweeter Apis give ..."
4,2019-04-07 06:53:38,4,NaN,1,"Other queries: ""do we have to make two differe..."
5,2019-04-07 05:32:27,5,NaN,1,"Other queries: ""If using Twitter api, it does ..."
6,2019-04-07 05:29:40,7,NaN,1,Response to some queries asked by students on ...
7,2019-04-06 17:11:29,19,NaN,2,RT @kdnuggets: Top 8 #Free Must-Read #Books on...
8,2019-04-06 16:43:27,17,1.0,3,@nupur_baghel @PennDATS Congratulation @nupur_...
9,2019-04-05 16:08:37,11,NaN,1,We have emailed the task details to all candid...
10,2019-04-05 04:05:11,49,NaN,16,RT @rfpvjr: Our NAACL paper on polarization in...
11,2019-04-05 04:04:43,21,1.0,11,RT @kdnuggets: Effective Transfer Learning For...
12,2019-04-03 18:31:53,222,NaN,59,RT @stanfordnlp: What’s new in @Stanford CS224...
13,2019-04-03 17:04:32,2369,NaN,851,RT @DeepMindAI: Today we're releasing a large-...
14,2019-04-03 09:03:40,150,NaN,16,RT @ylecun: Congratulations Jitendra Malik !\n...
15,2019-04-03 07:46:02,4,NaN,4,RT @IIITDelhi: Another chance to take admissio...
16,2019-04-02 04:20:13,8,NaN,1,Dear @midasIIITD internship candidates who hav...
17,2019-04-02 02:44:54,5,NaN,1,Looking forward to your paper submission to @I...
18,2019-04-02 02:35:44,9,NaN,7,RT @ngrams: Reproducibility in multimedia rese...
19,2019-04-01 06:53:08,7,NaN,2,Online application for https://t.co/DJFDrQsHZP...
20,2019-03-31 10:21:24,12,NaN,10,RT @ACMMM19: A final reminder of the Reproduci...
21,2019-03-29 19:43:24,7,NaN,2,RT @isarth23: Thanks for the support and help ...
22,2019-03-29 17:16:40,9,NaN,1,"Since SemEval-2019 will be held June 6-7, 2019..."
23,2019-03-29 17:04:30,2,NaN,0,+@aggarwal_kartik.\nCongrats! Wish you many mo...
24,2019-03-29 17:03:29,6,NaN,1,RT @aggarwal_kartik: Our work (@midasIIITD ) a...
25,2019-03-29 17:02:24,9,NaN,1,"Congratulations! @midasIIITD team, @isarth23 @..."
26,2019-03-29 05:35:22,0,NaN,0,@EEMLcommunity @radamihalcea too many deadline...
27,2019-03-28 16:55:01,1964,NaN,715,RT @stanfordnlp: CS224N Natural Language Proce...
28,2019-03-28 16:54:37,643,NaN,157,RT @ylecun: Learn PyTorch by running on Google...
29,2019-03-27 16:09:09,4,1.0,1,Dr. Vineeth N Balasubramanian will present a T...
...,...,...,...,...,...
306,2018-08-09 05:59:57,567,NaN,265,RT @TensorFlow: TensorFlow 1.10.0 has been rel...
307,2018-08-08 11:30:56,2,NaN,1,@midasIIITD is looking for motivated IIITD MTe...
308,2018-08-08 05:53:48,3,1.0,1,@IIITDelhi @ponguru @RatnRajiv The results of ...
309,2018-08-08 05:45:58,6,NaN,1,RT @IIITDelhi: @midasIIITD has secured rank 1 ...
310,2018-08-07 07:16:33,88,1.0,40,RT @kdnuggets: Comparison of Top 6 Python NLP ...
311,2018-08-07 02:05:12,1,NaN,1,Check more details of the 20th IEEE Internatio...
312,2018-08-07 01:58:49,1,NaN,1,MR2AMC@ISM 2018 will be organized by @RatnRaji...
313,2018-08-07 01:50:33,1,NaN,1,"Our workshop proposal named, ""MR2AMC: Multimod..."
314,2018-08-06 17:48:23,0,NaN,0,@NUSComputing Congratulations Abdelhak and Pro...
315,2018-08-06 17:46:59,424,1.0,103,RT @goodfellow_ian: One of the most anticipate...
316,2018-08-06 06:06:47,0,NaN,0,@the_dhumketu Great to have you in @midasIIITD
317,2018-08-03 05:56:33,6,NaN,1,Congratulation @soujanyaporia for being appoin...
318,2018-08-01 11:47:15,5,1.0,1,@IIITDelhi @the_dhumketu Thanks team @midasIII...
319,2018-08-01 11:20:07,7,NaN,4,RT @IIITDelhi: Congratulations @midasIIITD int...
320,2018-08-01 05:06:47,4,NaN,4,RT @learning_pt: Profile of the 5 Indian under...
321,2018-07-31 12:11:52,1,NaN,0,Have a look at the list of accepted papers in ...
322,2018-07-31 02:06:26,757,NaN,264,RT @goodfellow_ian: https://t.co/hYiWI7ntyk Te...
323,2018-07-30 07:30:51,14,NaN,2,RT @IIITDelhi: Congratulations Dr. @RatnRajiv ...
324,2018-07-28 11:07:11,217,NaN,57,"RT @ylecun: Jitendra Malik, who directs FAIR-M..."
325,2018-07-28 06:14:09,225,NaN,105,RT @kdnuggets: .@Bloomberg launches free cours...
326,2018-07-28 06:13:48,7,NaN,7,RT @TechAtBloomberg: Missed #PyLondinium18? Wa...
327,2018-07-28 04:08:21,36,NaN,6,RT @IIITDelhi: We are delighted to announce th...
328,2018-07-27 06:46:44,3,NaN,2,Get ready for the annual technical fest of @II...
329,2018-07-27 04:07:31,8,NaN,2,Congratulations Dr. @RatnRajiv and team @midas...
330,2018-07-25 05:14:35,5,NaN,1,Congratulations MIDAS @midasIIITD intern Prakh...
331,2018-07-24 10:33:23,2,NaN,1,MIDAS@IIITD foundation. https://t.co/LKuzyBHzjm
332,2018-07-24 10:12:34,2,NaN,1,It feels great to be the part of @IIITDelhi. h...
333,2018-07-24 09:46:26,4,1.0,1,"Thank you, @toonzratn for designing the logo o..."
334,2018-07-23 16:25:05,3,NaN,1,We are on Facebook too. Like our page to get o...
335,2018-07-23 12:53:15,7,NaN,4,MIDAS is a group of researchers at IIIT-Delhi ...